from Hello_GP_Lib import *

POPULATION_SIZE = 100
INDIVIDUALS_NUMBER_OF_TRAITS = 10
GENERATIONS_PER_RUN = 300  
TRAIT_CHANGE_PERCENTAGE = 3
PAIRS_OF_PARENTS_SAVED_FOR_ELITISM = 1
NUMBER_OF_ISLANDS = 5
MIGRATION_INTERVAL = 5
PAIRS_OF_IMMIGRANTS = 3
MAX_CHILDREN_KILLED = 10
CROWDING_DIST_THRESH = 1
CROWDING_NICHES = 30
FITNESS_SHARING_RANGE = 1

INIT_DEPTH = 4

treeGP = GP(
    populationSize=POPULATION_SIZE,
    initDepth=INIT_DEPTH,
    NT=NT,
    T=T
)

for _ in range(GENERATIONS_PER_RUN):

    treeGP.RunGen()
    
    treeGP.PlotGenerationalFitness()