# -*- coding: utf-8 -*-
"""neuralnets-sklearn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gP6rHd6XVpkKlHjJ2tCbo4IzQratOfbo
"""

import sklearn.neural_network as nn
import numpy as np

inputs = np.array([[0,0],[1,0],[0,1],[1,1]])
outputs = np.array([0,1,1,0])

net = nn.MLPClassifier(  max_iter=100000, hidden_layer_sizes=(2))

net.fit(inputs, outputs)

o = net.predict(inputs)

o

net.coefs_